# Title of Component (i.e. dbs)

## Components 

Link to Apollo Repository: https://github.com/apollo-business-automation/ibm-cp4ba-enterprise-deployment/tree/main/scripts/roles/cp4ba/tasks/predeploy:[you can find the original feature configured in Ansible here]

List the components and the relevant filepaths (i.e)

* A job that performs steps x, y and z to configure DB2 in the DB2 namespace http://github.com/oto-gitops/yourjoborbranchetc:[you can view find this feature here]
* a namespace YAML file that deploys a namespace 


## Deployment order
Add the sync wave/deployment order, and the reason for this
i.e. This job has a sync wave of 250 as it needs to happen after db2 is deployed, but before the cp4ba components are deployed


## Usage instructions / configurable parameters

* Add the parameters that need to be passed to your script, the jobspec or the yaml job etc. i.e. 
* *The YAML spec for the job takes two configurables:*  
    1. A list of users to create in the db2 openldap pod 
        - Configure these in the USER_LIST environment var
    2. a list of services that will be configured. 
        - configure these in the args passed in to the `-i` flag
[source, yaml]
```
apiVersion: batch/v1
kind: Job
metadata:
  name: database-configuration
  # can change this to cp4ba if we need to, but the job is ALL about configruing db2 for cp4ba so this seems like good separation to me. 
  namespace: db2
spec:
  template:
    spec:
      serviceAccountName: db2-configure-sa
      containers:
      - name: dbs-config
        image: quay.io/mikhail_nikitin1/db2init:latest # location the image is pushed to i.e. quay.io/langley_millard_ibm/repo_name
        command: ["./create_db.sh"]
        env:
        # CONFIGURE PARAMETERS HERE
        - name: USER_LIST
          value: "gcd,fpos,ros,icndb,os1"
        - name: KUBECONFIG
          value: "/tmp/config"
        args: ["-i", "BAN,FNCM,IER"]
        imagePullPolicy: Always
      restartPolicy: OnFailure
  backoffLimit: 2
  # path to preconfigure job git repo https://github.com/oto-cp4ba-gitops/dbs-configure-job
  # branch is origin/feature/multi-db-init-mn
```


## Closing statements and comments

add anything extra here